### ISSUE TITLE
Nondisclosure Terms

### ISSUE THREAD

**Issue by kemitchell** [kemitchell/blockchain-commons-patron-agreement#5]
@ChristopherA to date, have you signed NDAs with patrons and consulting clients? Have they asked you to do so?

**Comment by ChristopherA** [comment]
We have, but want to move to where it is the default.

**Comment by ChristopherA** [comment]
NOT the default

**Comment by kemitchell** [comment]
Hmm. Where the relationship has included consulting as well, have you tended to NDAs?

I'm thinking of the terms we discussed explaining that we will redact confidential information from prepared reports before publication. Ideally, NDA terms would apply to those confidential bits, but not to the rest.

**Comment by ChristopherA** [comment]
Yes, where they need advice on ecosystem, or how to fit the project into their own goals, they have to share with us about themselves. 

In old standard contract, we have a fairly long confidentiality section. I really want them to avoid giving us confidential information unless it is absolutely needed. 

-- Christopher Allen

> 5.1. General. A party's "Confidential Information" means the business, technical or other non-public information of a Party, and includes, (but is not limited to): information consisting of or relating to a Party's publications products, services, plans, names, de- signs, methods, finances, marketing plans, business opportunities, personnel, re- search, development or know-how, which is plainly marked as "confidential", "secret", “restricted”, or “non-public” ( for purposes of this Agreement “Confidential”), or any information of which is presented verbally and identified at the time is delivered as Confidential, so long as such designation is confirmed in writ- ing within a reasonable time after disclosure. A party’s “Proprietary Information” in- cludes any information owned or otherwise created by the party who furnishes it, which may not necessarily be Confidential Information in that may be publicly avail- able, but which is normally furnished under license or otherwise for restricted use, and where unrestricted use of such information does not transfer to the receiving par- ty. Proprietary Information includes (but is not limited to): software programs, com- puter information system designs or diagrams, data-sets, any information marked as “proprietary”, or any information which is designated verbally as such at the time de- livered, so long as such designation is confirmed in writing within a reasonable time after disclosure. Company agrees that it will not provide any Company-proprietary source code to Consultant unless it is expressly stated in a separate SOW.
5.2.Exclusions from Confidentiality. Notwithstanding the foregoing, "Confidential In- formation" and “Proprietary Information” will not include information that (a) is or becomes generally known or available by publication or otherwise through no fault of the receiving Party, (b) is or becomes part of the public domain through no fault of the receiving Party; (c) was rightfully in the receiving Party’s possession at the time of disclosure, without restriction as to use or disclosure; or (d) is rightfully received by the receiving Party during the term of this Agreement from a third party who had the right to disclose it and who provided it without restriction as to use or disclosure. For greater certainty, even if information is excluded from treatment as “Confiden- tial” under this Agreement, it may still be subject to use restrictions as “Proprietary”, if appropriate.
Permissible Disclosures- Due to Legal Requirements. A receiving party may disclose Confidential and Proprietary Information where such information is disclosed by re- quirement of a governmental agency or third party litigant as expressly required by operation of law, regulation, subpoena, or court order. In such case, if possible, re- ceiving party shall notify the disclosing party of the pending disclosure to allow the disclosing party to seek a protective order. In addition, for greater certainty, where law or regulation expressly permits or requires disclosure to a court or government agency under a “whistleblower” law (by way of example and not intended as an ex- haustive list: 18 U.S.C. Section 1833), such disclosure of Confidential or Proprietary information may be made as permitted under such law or regulation.
5.4.Treatment of Confidential and Proprietary Information. During the term of this Agreement and three (3) years after any termination or expiration of this Agreement, each party agrees that it will use the same efforts to protect the confidentiality of the other parties' Confidential Information as it uses to protect its own Confidential In- formation of a like nature, however no party shall use less than reasonable efforts to prevent disclosure or distribution of any of other party's' Confidential Information to any third party. Neither party shall use or duplicate any Confidential Information pro- vided hereunder except where such use or duplication is necessary to perform under this Agreement. Any Confidential Information or Proprietary Information disclosed or furnished as part of any engagement of Consultant is disclosed or furnished solely for the purpose of providing or making use of services under this Agreement, and may not otherwise be used by the receiving party for any other purpose without express written permission (including any licenses granted under this Agreement) of the own- er such information.
5.5.Special Relief. Each Party hereby stipulates and agrees that the other Party's remedy at law for damages for a violation of the provisions of Section 5 would be inadequate because the subject matter thereof is of unique and special importance to the other Party, and each Party hereby stipulates and agrees that the other Party shall, in addi- tion to such other remedies as may be available, be entitled to specific performance of such provisions and to injunctive relief with respect to any such violations thereof by the first Party or any matters related to any such violation.

**Comment by kemitchell** [comment]
> I really want them to avoid giving us confidential information unless it is absolutely needed.

I hear you. And that's fine.

Would you be alright with _conditional_ NDA terms in the patron that apply only if you sign a SOW for "consulting", and then only to information that the patron _needs_ to disclose in order to advance the consulting work?

**Comment by ChristopherA** [comment]
Yes, that can work.
